train:
	gcc colors.c \
		concept_table.c \
		enumerator.c \
		interpreter.c \
		lambda.c \
		pool.c \
		test_train.c \
		toy_data.c \
		type.c \
		../containers/*.c \
		-o moo.o

lambda:
	gcc colors.c \
		concept_table.c \
		extract.c \
		lambda.c \
		pool.c \
		test_lambda.c \
		-o moo.o

enumerator:
	gcc colors.c \
		concept_table.c \
		enumerator.c \
		interpreter.c \
		lambda.c \
		pool.c \
		test_enumerate.c \
		type.c \
		-o moo.o

pool:
	gcc colors.c pool.c test_pool.c -o moo.o
