lambda:
	gcc colors.c \
		concept_table.c \
		extract.c \
		lambda.c \
		pool.c \
		test_lambda.c \
		-o moo.o

enumerator:
	gcc colors.c \
		concept_table.c \
		enumerator.c \
		lambda.c \
		pool.c \
		test_enumerate_arc.c \
		type.c \
		-o moo.o

pool:
	gcc colors.c pool.c test_pool.c -o moo.o
